### ISSUE TITLE
The config values from RavenAppenderFactory class will overrite the "setters" in the RavenBootstrap class.

### ISSUE THREAD

**Issue by xytian315** [tradier/dropwizard-raven#18]

**Comment by xytian315** [comment]
Hi, I found a very interesting problem. The RavenBootstrap class seems not quite working well. The config values from RavenAppenderFactory class will overrite the "setters" in the RavenBootstrap class. 

Based on this line https://github.com/tradier/dropwizard-raven/blob/master/src/main/java/com/tradier/raven/logging/RavenBootstrap.java#L85 
"threshold" in the RavenAppenderFactory should set it to be "LEVEL.ERROR".  and sentry should get all the "ERROR" messages due to this line https://github.com/tradier/dropwizard-raven/blob/master/src/main/java/com/tradier/raven/logging/RavenAppenderFactory.java#L126
But after integrating the library into my dropwizard app, I found out it is actually reading from config file.
My config file looks like:
``` 
logging:
  level: INFO
appenders:
  - type: console
  - type: raven
    dsn: https://user:pass@getsentry.com/appid
    environment: production
    release: 1.0.0
    serverName: 10.0.0.1
    tags: tag:value,tag2:value
```
The sentry will get all the "INFO" instead of "ERROR". 

To further demonstrate this, I went ahead to hardcode "release" in the bootstrap class to be "1.1.0", I kept the config for my dropwizard app to be "1.0.0". Sentry will get all the messages tagged to be "1.0.0", which is from my config file. 

Looking forward to your feedback.
