### ISSUE TITLE
Failed to parse configuration at: logging.appenders.

### ISSUE THREAD

**Issue by siddjain** [tradier/dropwizard-raven#6]
Get this error while trying to use library:

```
Failed to parse configuration at: logging.appenders.[1]; Could not resolve type id 'raven' into a subtype of [simple type, class io.dropwizard.logging.AppenderFactory]: known type ids = [AppenderFactory, console, file, syslog]
 at [Source: N/A; line: -1, column: -1] (through reference chain: com.company.launcher.WebServiceConfiguration["logging"]->io.dropwizard.logging.LoggingFactory["appenders"]->java.util.ArrayList[1])
```

contents of config.yml

```
logging:
  level: INFO
  appenders:
    - type: console
    - type: raven
      dsn: http://XXX
```
